spring:
  application:
    name: main-microservice
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/gym_db}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:root}"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}"
    show-sql: true
  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"
      password: "${REDIS_PASSWORD:}"
eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      reportsMicroserviceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: PT30S
        failureRateThreshold: 50
  retry:
    retry-aspect-order: 2
    instances:
      reportsMicroserviceRetry:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 5s
application:
  reports-microservice:
    base-url: http://reports-microservice
  logging:
    transaction-id:
      key: "tx.id"
      value: "DB Transaction Id: [%s]"
      header: "Transaction-ID"
  security:
    token:
      expiration-period: 43200000
      secret-key: 6u21QAFzzxbE4v9y8cVyE73vTnHgdb0jn3APHdwJESJaY8nQxNYFaSejvXiU
  front-end:
    host: "${FRONTEND_HOST:}"
