spring:
  datasource:
    hikari:
      max-lifetime: 840000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
management:
  endpoint:
    health:
      show-details: NEVER
  endpoints:
    web:
      exposure:
        include:
          - health
