spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
management:
  endpoint:
    health:
      show-details: NEVER
  endpoints:
    web:
      exposure:
        include:
          - health
