server:
  port: 8081
spring:
  application:
    name: reports-microservice
eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
application:
  messaging:
    queue:
      update-trainer-workload: "${UPDATE_WORKLOAD_QUEUE:reports.trainer-workload.update.queue}"
  logging:
    transaction-id:
      key: "tx.id"
      value: "DB Transaction Id: [%d]"
      header: "Transaction-ID"
